// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqoeiwepkbnmvdydhmvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxb2Vpd2Vwa2JubXZkeWRobXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTY5ODgsImV4cCI6MjA2ODA5Mjk4OH0.Fx63uQG1M1xM5kFsPWXMun49LbAZ_B_Cq73Ks3UV8og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});